### ISSUE TITLE
Website copy edits Feb 10, 2020

### ISSUE THREAD

**Issue by tiffrobo** [OnionBrowser/onionbrowser.github.io#11]
**Landing page**

- [x] Remove “Targeted ads are history.” from the last line under “The highest standard of privacy”

- [ ] Make the +more button static. No link.
- [x] Remove 'Always' from "Browsing is always private"

**About page**
- [x] Update the spelling of: Surveillance 

- [x] Add a colon to the Disclaimer section, first paragraph, last sentence. “Please remember the following:”

- [ ] Add three bullet points with this copy after “Please remember the following:” 

- Apple requires all web browser apps to use the same core web rendering ending, called UIWebKit or WKWebView. Due to this limitation, we are unable to compile and include our own web engine, based on Firefox Gecko, that other browsers, like Tor Browser on desktop for Android, are allowed to do.

- Onion Browser only tunnels traffic within the Onion Browser app. If you are using a smartphone be aware that information outside of Onion Browser is not protected. 

- If you use Onion Browser to log into websites that you sometimes log into without Tor (i.e. Facebook), the website will know who you are and know that you are using Tor. In certain circumstances (i.e. political dissents in repressive nations), this may be incriminating.

**Privacy page**

- [x] Add periods to the last three paragraphs after the links. 

**Legal page**

 **Replace sentence:** 
- [x] From: “This software uses strong cryptography and may it fall under certain export/import and/or use restrictions in some other parts of the world.”
- [x] To: “This software uses strong cryptography and may fall under certain export/import and/or use restrictions in some other parts of the world.”

**Replace sentence:**
- [x] From: “If you are a developer and plan on redistributing this app in source or binary form, please see read the LICENSE file (1.X; 2.X (https://onion-preview.netlify.com/legal)) for full license details and legal obligations.“
- [x] To: “If you are a developer and plan on redistributing this app in source or binary form, please read the LICENSE file (1.X; 2.X (https://onion-preview.netlify.com/legal)) for full license details and legal obligations.“

**Broken or not linked, links**
- [ ]         Need Mozilla Public License 2.0 (MPL) link
- [ ]         Add Endless / Onion Browser License (OBL) (https://github.com/mtigas/OnionBrowser/blob/2.X/LICENSE) as link
- [x]         Add 1.X; (https://github.com/mtigas/OnionBrowser/blob/1.X/LICENSE) as link
- [x]         Add 2.X (https://github.com/mtigas/OnionBrowser/blob/2.X/LICENSE) as link

**Comment by tiffrobo** [comment]
Landing Page

- [ ] Remove 'Always' from "Browsing is always private"

**Comment by n8fr8** [comment]
are these the latest? or newer ones on google doc?

**Comment by tiffrobo** [comment]
These are the latest for the website. The FAQ is separate. I was going to make the changes in github now. Would you like me to?

**Comment by tiffrobo** [comment]
@n8fr8 if you'd like me to make changes and do a pull request will you point me to the correct repo, please?

**Comment by m4mb01t4l14n0** [comment]
I've made the requisite edits, but with two caveats:
(1) on the landing page, I am not sure how to make the MORE button static
(2) on the about page, I believe I've used the proper YAML technique to create an embedded list with the 3 "bullet points" requested.  But,this is my first time using YAML and I may have done that incorrectly.  I'll appreciate a review of this.

**Comment by tiffrobo** [comment]
@m4mb01t4l14n0 
1) I just need the link removed. Should say the word +more.
2) I can't actually help with this :) @n8fr8 could you ensure this is correct, please?

**Comment by tiffrobo** [comment]
@m4mb01t4l14n0 I've checked the boxes of things completed. Thanks for working on this. A few things still need to be completed.

**Comment by m4mb01t4l14n0** [comment]
@tiffrobo on "about" page, I used "..." instead of ":" because ":" is a reserved character in YAML.  The new sentences are there.  On "legal" page, sentences are updated and new links added.  There is a link description not mentioned, this is not a link and I will fix that.  On "landing" I don't even seen "more" anymore.  When I made the YAML change there it seems to have taken away the item completely.  Can you review all please?

**Comment by tladesignz** [comment]
Yeah, let's close this. Seems pretty stale, anyway.
