### ISSUE TITLE
Donate > Support Onion Browser: Feature not functional

### ISSUE THREAD

**Issue by Nishant-Taksande** [OnionBrowser/onionbrowser.github.io#17]
**Link:**
https://guardianproject.github.io/onionbrowser-website-dev/

**Steps to Reproduce:**

1. Click on above link
2. Click on Donate button
3. Select amount say "Send $20.00 USD"
4. Click on Donate

**Expected:**
Feature should be functional

Actual:
Feature is not functional

**Video:**
https://monosnap.com/file/ZI3vDDxxTmZt4da4B8bEVZ4ueB62f2

**Comment by 8pen-s8urce** [comment]
PayPal isn't a donation method anymore, this issue can be closed.

**Comment by tladesignz** [comment]
You're the cleaner, @8pen-s8urce! 😜

**Comment by 8pen-s8urce** [comment]
> You're the cleaner, @8pen-s8urce! 😜

That is my intention. 😄
