### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by cstiens** [OnionBrowser/onionbrowser.github.io#34]
Here are some questions to consider addressing:

Q1: Should any benefits related strictly to the connection over Tor
(like hiding the IP) be counted as benefits of using Onion Browser
specifically? Does Safari work differently in this regard?

Q2: Does Onion Browser provide better protection against privacy-,
security- or anonymity-harming behaviour from Apple than Safari does,
and how?

Q3: What other general improvements does Onion Browser make to security,
privacy, or usability which can’t be replicated on Safari?

Q4: How does the fingerprint of Onion Browser differ from Safari, and
how does that impact fingerprinting protection?

Q5: Which privacy or security improvements can any iOS-browser that's
not controlled by Apple make? What exactly is the extent to which
restrictions from Apple fundamentally limit such improvements?

Q6: What are the advantages of using Onion Browser instead of Safari?

**Comment by tladesignz** [comment]
Perfect day to take care of something like this!
